---

- name: Install docker-py
  pip: name=docker-py executable=/home/core/pypy/bin/pip

- name: Install httplib2
  pip: name=httplib2 executable=/home/core/pypy/bin/pip

- name: Set /etc/hosts to enable local hostname resolution (for Mesos DNS and Marathon)
  become: yes
  become_user: root
  template: src=CoreOS/hosts.j2 dest=/etc/hosts

- name: Create /etc/systemd/system/docker.service.d folder
  become: yes
  become_user: root
  file:
    path: /etc/systemd/system/docker.service.d/
    state: directory

- name: Increase ulimit
  become: yes
  become_user: root
  template: src="{{ansible_os_family}}/30-increase-ulimit.conf.j2" dest=/etc/systemd/system/docker.service.d/30-increase-ulimit.conf

- name: Allow insecure registry
  become: yes
  become_user: root
  template: src="{{ansible_os_family}}/50-insecure-registry.conf.j2" dest=/etc/systemd/system/docker.service.d/50-insecure-registry.conf

- name: Ensure systemd is reloaded after 30-increase-ulimit.conf and 50-insecure-registry.conf have been added
  become: yes
  become_user: root
  shell: systemctl daemon-reload

- name: Restart Docker service
  become: yes
  become_user: root
  raw: systemctl restart docker.service