---
- name: Add the repository
  yum: name=http://repos.mesosphere.com/el/7/noarch/RPMS/mesosphere-el-repo-7-1.noarch.rpm

- name: Install mesos
  yum: name=mesos update_cache=yes

- name: Stop mesos-master
  service: name=mesos-master state=stopped
  when: "'masters' not in group_names"

- name: Disable mesos-master
  command: systemctl disable mesos-master.service
  when: "'masters' not in group_names"

- name: Set zookeeper address for mesos
  template: src=zk.j2 dest=/etc/mesos/zk
  notify:
    - Restart mesos-slave

- name: Set hostname
  template: src=hostname.j2 dest=/etc/mesos-slave/hostname
  notify:
    - Restart mesos-slave

- name: Set IP
  template: src=ip.j2 dest=/etc/mesos-slave/ip
  notify:
    - Restart mesos-slave

- name: Mesos containerizers
  template: src=containerizers.j2 dest=/etc/mesos-slave/containerizers
  notify:
    - Restart mesos-slave

- name: Mesos executor_registration_timeout
  template: src=executor_registration_timeout.j2 dest=/etc/mesos-slave/executor_registration_timeout
  notify:
    - Restart mesos-slave

- name: Set LIBPROCESS_IP env
  lineinfile:
    dest: /etc/default/mesos
    regexp: "^LIBPROCESS_IP"
    line: "LIBPROCESS_IP={{ ansible_ssh_host }}"
  notify:
    - Restart mesos-slave
  when: "'masters' not in group_names"

- name: Set LIBPROCESS_ADVERTISE_IP env
  lineinfile:
    dest: /etc/default/mesos
    regexp: "^LIBPROCESS_ADVERTISE_IP"
    line: "LIBPROCESS_ADVERTISE_IP={{ ansible_ssh_host }}"
  notify:
    - Restart mesos-slave
  when: "'masters' not in group_names"

- name: Start mesos-slave
  service: name=mesos-slave state=started