---

# Install ZooKeeper
- name: Pull Zookeeper container
  raw: docker pull {{ registry_config.hostname }}:{{ registry_config.port }}/{{ docker.images.zookeeper | basename }}

- name: Make sure Zookeeper is configured
  template: src=zookeeper/zookeeper.service.j2 dest=/etc/systemd/system/zookeeper.service

- name: Ensure systemd is reloaded if zookeeper.service has changed
  shell: systemctl daemon-reload

- name: (Re)start zookeeper.service
  shell: systemctl restart zookeeper.service

- name: Make sure Zookeeper is running and enabled
  service: name=zookeeper.service state=running enabled=yes

# Install Mesos Master
- name: Pull Mesos Master container
  raw: docker pull {{ registry_config.hostname }}:{{ registry_config.port }}/{{ docker.images.master | basename }}

- name: Create folder /var/tmp/mesos/master for Mesos master on host
  file:
    path: /var/tmp/mesos/master
    state: directory

- name: Create folder /var/log/mesos/master for Mesos master on host
  file:
    path: /var/log/mesos/master
    state: directory

- name: Make sure Mesos Master is configured
  template: src=master/mesos-master.service.j2 dest=/etc/systemd/system/mesos-master.service

- name: Ensure systemd is reloaded if mesos-master.service has changed
  shell: systemctl daemon-reload

- name: (Re)start mesos-master.service
  shell: systemctl restart mesos-master.service

- name: Make sure Mesos Master is running and enabled
  service: name=mesos-master.service state=running enabled=yes

# Install Marathon
- name: Pull Marathon container
  raw: docker pull {{ registry }}/{{ docker.images.marathon | basename }}

- name: Make sure Marathon is configured
  template: src=marathon/marathon.service.j2 dest=/etc/systemd/system/marathon.service

- name: Ensure systemd is reloaded if marathon.service has changed
  shell: systemctl daemon-reload

- name: (Re)start marathon.service
  shell: systemctl restart marathon.service

- name: Make sure Marathon is running and enabled
  service: name=marathon.service state=running enabled=yes